version: "3.8"

services:
  devout-bot:
    build: .
    container_name: devout-bot
    restart: unless-stopped
    ports:
      - "8047:8045"
    env_file:
      - .env
    volumes:
      - bot_data:/app/data

volumes:
  bot_data: