services:
  devout-bot:
    build:
      context: .
      args:
        BOT_PORT: "8045"   # container ichidagi uvicorn port
    image: devout-devout-bot:latest
    container_name: devout-bot
    restart: unless-stopped
    ports:
      - "6000:8045"        # host 6000 → container 8045
    env_file:
      - .env
    volumes:
      - bot_data:/app/data

volumes:
  bot_data:
